FROM logstash:7.9.1
RUN rm -f /usr/share/logstash/pipeline/logstash.conf \
    && mkdir -p /usr/share/logstash/patterns
COPY pipeline/ /usr/share/logstash/pipeline/
COPY config/ /usr/share/logstash/config/
COPY patterns/ /usr/share/logstash/patterns/